### ISSUE TITLE
Typo cause page.pages not working

### ISSUE THREAD

**Issue by LazyZhu** [codestacks/jekyll-category-pagination#3]
https://github.com/codestacks/jekyll-category-pagination/blob/master/paginator.rb#L110

**Comment by Marloto** [comment]
Hi LazyZhu,

can you explain this a little bit? Which kind of typo causes page.pages not working?

Best regards,
Marloto

**Comment by LazyZhu** [comment]
As 'page.pages' means the maximum number of pages, Thus the line should be `pages = (list.length / detail['pagination']).ceil` not `pages = (detail['pagination'] / list.length).ceil`

**Comment by Marloto** [comment]
Thx! Sorry for delay... Issue fixed
